name: Argonaut
version: ${project.version}
authors:
  - Dragovorn
api-version: "1.15"
main: com.dragovorn.argonaut.core.ArgonautCorePlugin
softdepend:
  - ProtocolLib
commands:
  argonaut:
    aliases:
      - a
      - ag
    description: Base command for argonaut